#!/bin/sh

# This actually works on the test code.
# Several things have to happen first.
# 
# 1. jxta must be installed:  make install 
# 2. APR must point to wherever apr was installed (look for libapr*).
# 3. Build and run:
#    $ gcc -c pa_test.c  `../jxta-config  --cflags` 
#    $ gcc  pa_test.o -o pa_test  `../jxta-config  --libs`
#    $ ./pa_test PGA.xml
#
# pa_test.c and PGA.xml are in the jxta-c/test directory




##  This hardwired stuff needs to be fixed to allow the 
##  programmer to set the options on the command line.
prefix=$HOME
#apr_prefix=/home/dave/src/jxta/jxta-c
#apr_prefix=/$HOME/src/jxta/jxta-c
apr_prefix=$APR 
exec_prefix=${prefix}
exec_prefix_set=no

###  Probably won't work yet.
jxta_libs="-L${prefix}/lib -ljxta -L${apr_prefix}/lib/apr/lib -lapr -lpthread -lcrypt -ldl -laprutil -lgdbm -ldb1 -lexpat"
jxta_cflags="-I${prefix}/include -I${apr_prefix}/lib/apr/include"


usage()
{
	cat <<EOF
Usage: jxta-config [OPTIONS] [LIBRARIES]
Options:
	[--prefix[=DIR]]
        [--apr_prefix[=DIR]]
	[--exec-prefix[=DIR]]
	[--version]
	[--libs]
	[--cflags]
Libraries:
	jxta
EOF
	exit $1
}

if test $# -eq 0; then
	usage 1 1>&2
fi


##  APR is the apache portable runtime.  If the user
##  sets APR with the location, use it.
if test $APR ; then
  apr_prefix=$APR
else
  echo "Environment variable APR must point to where apr is installed."
  exit 1
fi


lib_jxta=yes

while test $# -gt 0; do
  case "$1" in
  -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
  *) optarg= ;;
  esac

  case $1 in
    --prefix=*)
      prefix=$optarg
      echo $prefix
      if test $exec_prefix_set = no ; then
        exec_prefix=$optarg
      fi
      ;;
    --prefix)
      echo_prefix=yes
      ;;
    --apr_prefix=*)
      apr_prefix=$optarg
      ;;
    --apr_prefix)
      echo_apr_prefix=yes
      ;;
    --exec-prefix=*)
      exec_prefix=$optarg
      exec_prefix_set=yes
      ;;
    --exec-prefix)
      echo_exec_prefix=yes
      ;;
    --version)
      echo 0.0
      ;;
    --cflags)
      echo_cflags=yes
      ;;
    --libs)
      echo_libs=yes
      ;;
    jxta)
      lib_jxta=yes
      ;;
    *)
      usage 1 1>&2
      ;;
  esac
  shift
done

if test "$echo_prefix" = "yes"; then
	echo $prefix
fi

if test "$echo_exec_prefix" = "yes"; then
	echo $exec_prefix
fi

if test "$echo_cflags" = "yes"; then
      echo  $jxta_cflags 
fi

if test "$echo_apr_prefix" = "yes"; then
      echo -I${apr_prefix}
fi



if test "$echo_libs" = "yes"; then
      my_jxta_libs=
      libdirs=-L${exec_prefix}/lib
      for i in $jxta_libs ; do
        if test $i != -L${exec_prefix}/lib ; then
          if test -z "$my_jxta_libs" ; then
            my_jxta_libs="$i"
          else
            my_jxta_libs="$my_jxta_libs $i"
          fi
        fi
      done

      echo $libdirs -L/usr/X11R6/lib -lgtk -lgdk $my_jxta_libs 
fi      

