/*
 * Copyright (c) 2002 Sun Microsystems, Inc.  All rights
 * reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *
 * 3. The end-user documentation included with the redistribution,
 *    if any, must include the following acknowledgment:
 *       "This product includes software developed by the
 *       Sun Microsystems, Inc. for Project JXTA."
 *    Alternately, this acknowledgment may appear in the software itself,
 *    if and wherever such third-party acknowledgments normally appear.
 *
 * 4. The names "Sun", "Sun Microsystems, Inc.", "JXTA" and "Project JXTA" must
 *    not be used to endorse or promote products derived from this
 *    software without prior written permission. For written
 *    permission, please contact Project JXTA at http://www.jxta.org.
 *
 * 5. Products derived from this software may not be called "JXTA",
 *    nor may "JXTA" appear in their name, without prior written
 *    permission of Sun.
 *
 * THIS SOFTWARE IS PROVIDED ``AS IS'' AND ANY EXPRESSED OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES
 * OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED.  IN NO EVENT SHALL SUN MICROSYSTEMS OR
 * ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF
 * USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 * ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT
 * OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
 * SUCH DAMAGE.
 * ====================================================================
 *
 * This software consists of voluntary contributions made by many
 * individuals on behalf of Project JXTA.  For more
 * information on Project JXTA, please see
 * <http://www.jxta.org/>.
 *
 * This license is based on the BSD license adopted by the Apache Foundation.
 *
 * $Id$
 */

#ifndef JXTA_BUILTINMODULES_PRIVATE_H
#define JXTA_BUILTINMODULES_PRIVATE_H

#include "jxta_module.h"

#ifdef __cplusplus
extern "C" {
#if 0
};
#endif
#endif

typedef Jxta_module *(Jxta_module_instantiator) (void);

typedef struct {
    const char *name;
    Jxta_module_instantiator *instantiator;
} Jxta_builtinmodule_record;

/*
 * This table is (or should be) autogenerated in jxta_builtinmodules.c
 */
extern Jxta_builtinmodule_record jxta_builtinmodules_tbl[];

extern Jxta_module *jxta_endpoint_service_new_instance(void);
extern Jxta_module *jxta_rdv_service_new_instance(void);
extern Jxta_module *jxta_resolver_service_ref_new_instance(void);
extern Jxta_module *jxta_discovery_service_ref_new_instance(void);
extern Jxta_module *jxta_transport_http_new_instance(void);
extern Jxta_module *jxta_transport_tcp_new_instance(void);
extern Jxta_module *jxta_transport_tls_new_instance(void);
extern Jxta_module *jxta_netpg_new_instance(void);
extern Jxta_module *jxta_stdpg_new_instance(void);
extern Jxta_module *jxta_router_client_new_instance(void);
extern Jxta_module *jxta_pipe_service_new_instance(void);
extern Jxta_module *jxta_membership_service_null_new_instance(void);
extern Jxta_module *jxta_peerinfo_service_new_instance(void);
extern Jxta_module *jxta_transport_relay_new_instance(void);
extern Jxta_module *jxta_srdi_service_ref_new_instance(void);


#ifdef __cplusplus
#if 0
{
#endif
}
#endif

#endif /* JXTA_BUILTINMODULES_PRIVATE_H */

/* vi: set ts=4 sw=4 tw=130 et: */
